### ISSUE TITLE
删除数据时崩溃

### ISSUE THREAD

**Issue by wangfumm** [OnexZgj/ForYou#3]
删除唯一的一条数据时崩溃

部分错误信息：java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2e7491e position=0 id=-1, oldPos=2, pLpos:2 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{abe99c5 VFED..... .F....I. 0,0-1080,1812 #7f0800ac app:id/rv_fu_list}, adapter:com.it.onex.foryou.fragment.undone.UndoneAdapter@56ea571, layout:android.support.v7.widget.LinearLayoutManager@ceb0f56, context:com.it.onex.foryou.MainActivity@4b76048

**Comment by OnexZgj** [comment]
我这边测试机型是小米 5s ，没有发现如上的错误，你下载一下最新的apk，然后试一下，如果不行的话：请参考这个链接 https://blog.csdn.net/lovexieyuan520/article/details/50537846，看看问题是否可以解决，如果还出现如上bug，请及时联系我
